name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run:
        cd 530frontend
        npm install
        npm run build
    - run:
        npm install
        npm i pm2
        pm2 kill
        pm2 start app.js
        pm2 save
        sudo service nginx restart
